apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  annotations:
    kubernetes.io/change-cause: "deployeing v1.1"
spec:
   replicas: 3
   selector:
     matchLabels:
        app: myapp
   template:
     metadata:
        labels:
          app: myapp
     spec: 
       containers:
       - name: con1
         image: httpd:latest
         ports:
         - containerPort: 80
         resources:
            requests:
               cpu: "200m"
               memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123
  selector:
    app: myapp
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mydep
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydep
  targetCPUUtilizationPercentage: 70
