apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep-liv-tcp
spec:
   replicas: 3
   selector:
     matchLabels:
        app: myapp
   template:
     metadata:
        labels:
          app: myapp
     spec: 
       containers:
       - name: con1
         image: httpd:latest
         ports:
         - containerPort: 80
         livenessProbe:
           tcpSocket:
             port: 80
           initialDelaySeconds: 10
           periodSeconds: 5
