apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: man-pod
  annotations:
     describe: test pod created 
spec:
  containers:
  - image: nginx:latest
    name: con1 
    ports:
    - containerPort: 80
  nodeName: ip-172-20-10-211.ap-south-1.compute.internal
