apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: pod-nodesel
  annotations:
     describe: test pod created 
spec:
  containers:
  - image: nginx:latest
    name: con1 
    ports:
    - containerPort: 80
  nodeSelector:
    cpu: ryzen
