apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: node-aff-req
  annotations:
     describe: test pod created 
spec:
  containers:
  - image: nginx:latest
    name: con1 
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cpu
            operator: NotIn
            values:
            - ryzen
