apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: pod-aff-pre
  annotations:
     describe: test pod created 
spec:
  containers:
  - image: nginx:latest
    name: con1 
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - myapp
          topologyKey: kubernetes.io/hostname
