apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
    env: dev
  name: mypod
spec:
  containers:
  - image: httpd:latest
    name: con1
    ports:
    - containerPort: 80
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080

