apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod-sa
  annotations:
     describe: test pod created 
spec:
  serviceAccountName: demo-sa
  containers:
  - image: nginx:latest
    name: con1 
    ports:
    - containerPort: 80
