apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-2
spec:
   replicas: 1
   selector:
     matchLabels:
        app: wordpress-2
   template:
     metadata:
        labels:
          app: wordpress-2
     spec:
       containers:
       - name: con1-2
         image: wordpress:latest
         ports:
         - containerPort: 80
         env:
         - name: WORDPRESS_DB_HOST
           value: mysql-svc
         - name: WORDPRESS_DB_USER
           value: root
         - name: WORDPRESS_DB_PASSWORD
           value: test123
         - name: WORDPRESS_DB_NAME
           value: testdb
         - name: WORDPRESS_TABLE_PREFIX
           value: wp_2__
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30124
  selector:
    app: wordpress-2
  type: NodePort

