apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
spec:
   replicas: 1
   selector:
     matchLabels:
        app: mydb
   template:
     metadata:
        labels:
          app: mydb
     spec: 
       containers:
       - name: con1
         image: nginx:latest
         ports:
         - containerPort: 80
         volumeMounts:
         - name: myvol
           mountPath: /data
       volumes:
       - name: myvol
         secret:
           secretName: myfile
