apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: devops
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 800m
    defaultRequest:
      memory: 256Mi
      cpu: 150m
    type: Container
