apiVersion: v1
kind: ResourceQuota
metadata:
  name: rs-quota-devops
  namespace: devops
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    configmaps: "10"
    services: "10"
    secrets: "10"
    count/deployments: "10"
    count/replicationcontrollers: "100"
    count/statefulsets.apps: "10"
    count/pods: "50"
