apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep-dep
spec:
   replicas: 3
   selector:
     matchLabels:
        app: myweb
   template:
     metadata:
        labels:
          app: myweb
     spec: 
       containers:
       - name: con1
         image: httpd:latest
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  ports:
  - port: 80
  selector:
    app: myweb
 

